# -*- coding: utf-8 -*-
"""hackerrank codes

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KdVgNxSxqI4G5MsRuM6l6Z0fxGCOQwbL
"""

#hackerrank if-else problem
if __name__ == '__main__':
    n = int(input().strip())
if n%2 !=0:
 print("Weird")
elif n%2==0 and n>2 and n<=5:
 print("Not Weird")
elif n%2==0 and n>6 and n<=20:
 print("Weird")
else:
 print("Not Weird")

#arthemetic operators
if __name__ == '__main__':
    a = int(input())
    b = int(input())
    print(a+b)
    print(a-b)
    print(a*b)

#divisions
if __name__ == '__main__':
    a = int(input())
    b = int(input())
    print(a//b)
    print(a/b)

if __name__ == '__main__':
    n = int(input())
    for i in range(n):
        print(i**2)

# Second greatest in given numbers
if __name__ == '__main__':
    n = int(input())
    arr = map(int, input().split())
    arr1 = set(arr)
    arr2 = sorted(arr1)
    print(arr2[-2])

#consecutive values has a string
if __name__ == '__main__':
    n = int(input())
    for i in range (1, n+1):
        print(i,end='')